export const countries = [
    { id: 1, name: "United States" },
    { id: 2, name: "China" },
    { id: 3, name: "Russia" },
    { id: 4, name: "Germany" },
    { id: 5, name: "United Kingdom" },
    { id: 6, name: "France" },
    { id: 7, name: "Japan" },
    { id: 8, name: "India" },
    { id: 9, name: "Brazil" },
    { id: 10, name: "Canada" },
    { id: 11, name: "Italy" },
    { id: 12, name: "Australia" },
    { id: 13, name: "South Korea" },
    { id: 14, name: "Spain" },
    { id: 15, name: "Mexico" },
    { id: 16, name: "Turkey" },
    { id: 17, name: "Indonesia" },
    { id: 18, name: "Saudi Arabia" },
    { id: 19, name: "South Africa" },
    { id: 20, name: "Argentina" },
    { id: 21, name: "Netherlands" },
    { id: 22, name: "Switzerland" },
    { id: 23, name: "Sweden" },
    { id: 24, name: "Poland" },
    { id: 25, name: "Belgium" },
    { id: 26, name: "Norway" },
    { id: 27, name: "Austria" },
    { id: 28, name: "Thailand" },
    { id: 29, name: "United Arab Emirates" },
    { id: 30, name: "Singapore" },
    { id: 31, name: "Malaysia" },
    { id: 32, name: "Vietnam" },
    { id: 33, name: "Egypt" },
    { id: 34, name: "Iran" },
    { id: 35, name: "Pakistan" },
    { id: 36, name: "Ukraine" },
    { id: 37, name: "Colombia" },
    { id: 38, name: "Philippines" },
    { id: 39, name: "Bangladesh" },
    { id: 40, name: "Kazakhstan" },
  ];
